feat: changed implementation of keychain wrapper to use Keychainaccess lib
GoodRequest/GoodPersistence pull request #3
Opened 2024-02-28 15:36 UTC by sebastianmraz

2024-02-29 14:33 UTC, andrej-jasso requested changes
Komentare :) Tie budu dolezite v buducnosti hlavne keby si tam popisat vsetky tie corner cases a limitacie

2024-02-29 14:33 UTC, andrej-jasso commented on Sources/GoodPersistence/BoolExtensions.swift
Ak sa uz nepouziva takato hodnota tak vymaz ;)

2024-02-29 14:33 UTC, andrej-jasso commented on Sources/GoodPersistence/KeychainValue.swift
> +                // Retrieve data from Keychain using the key and accessibility if specified
Edit tych komentaro este a pis o tom preco nieco robi nie co sa tam deje.

To co sa tam deje je jasne z kodu. To preco sa to tak robi je enigmou :)

2024-02-29 14:33 UTC, andrej-jasso commented on Sources/GoodPersistence/KeychainValue.swift
>          set(newValue) {
Tu pre zmenu chybaju komentare

2024-03-01 12:08 UTC, plajdo commented on Sources/GoodPersistence/KeychainValue.swift
je tu wrapper pre `wrappedValue`, ale chyba `projectedValue`

v sample projekte vytvaras lazy publisher z `@KeychainValue` wrapnutej premennej - staci to dat priamo do toho a mozes pouzivat tu "SwiftUI-kovu" syntax cez `$value` ako publisher

2024-03-01 12:11 UTC, plajdo commented
vies pozriet aj #2 spolu s tymto? Ked uz sa prepisuju tie property wrappery 😄

2024-03-04 13:01 UTC, andrej-jasso approved these changes

2024-03-04 13:01 UTC, andrej-jasso commented on Sources/GoodPersistence/BoolExtensions.swift
toto stale existuje ?

2024-03-06 07:34 UTC, merged